Emit OpLine before OpFunction
KhronosGroup/glslang pull request #2321
Opened 2020-07-05 18:52 UTC by inequation

This ensures useful source line association for other tools, such as [AMDVLK's fork of SPIRV-LLVM-Translator](https://github.com/GPUOpen-Drivers/llpc/blob/2bd4eb104a93a61614f398826814e60cfc312fbc/llpc/translator/lib/SPIRV/SPIRVToLLVMDbgTran.cpp#L64). After this change, source file name information survives the entire compilation pipeline, from source to the DWARF info in the AMDGPU ELF.

Still working on tests.

2020-07-05 18:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2321) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2321) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=2321) it.</sub>

2021-02-25 20:07 UTC, inequation commented
Apologies for taking so long, I just resurrected the project that I need this for after a hiatus. I've updated the test suite to account for the newly added line statements.

2021-03-15 23:35 UTC, greg-lunarg commented
Sorry for the delay. Looking now...

2021-03-18 00:14 UTC, greg-lunarg requested changes
Thanks for the submission! One possible correctness issue, one small inefficiency and one variable rename.

2021-03-18 00:14 UTC, greg-lunarg commented on Test/baseResults/hlsl.pp.line2.frag.out
> +                              Line 1 23 0
Shouldn't this be Line 11 23 0?

2021-03-18 00:14 UTC, greg-lunarg commented on Test/baseResults/hlsl.pp.line2.frag.out
> +                              Line 11 23 0
Curious why we are getting two OpLines here now? Not a big deal, but this is coming through in the actual SPIR-V as well, so if this could be cleaned up easily, that would be nicer.

2021-03-18 00:14 UTC, greg-lunarg commented on SPIRV/SpvBuilder.h
> +    std::unordered_map<std::string, size_t> functionNames;
Maybe a better name: functionIndex?

2022-05-18 23:45 UTC, qingyuanzNV commented
Hi, is this PR still going? We have an internal patch which aims the exactly same thing with a slightly different approach (we set the line info in TGlslangToSpvTraverser::visitAggregate). What's the expected direction on this?

2022-05-19 06:54 UTC, inequation commented
Hi @qingyuanzNV! Personally, I have no resources right now to bring this to fruition. If you do, please go ahead and get yours integrated!

2023-04-01 01:55 UTC, arcady-lunarg commented
This was implemented in #2950.

2023-04-01 01:55 UTC, closed without merging