Cannot specify atomic counter with location.
KhronosGroup/glslang pull request #2525
Opened 2021-02-07 09:47 UTC by ZhiqianXia

glslang don't report the errors: atomic counter can not specified with location.

`
#version 310 es
precision highp float;
layout(location = 3, binding = 0, offset = 0) uniform atomic_uint uni0;
in highp vec4 dEQP_Position;
out float out0;

void main()
{
out0 = 0.0;
gl_Position = dEQP_Position;
}

`

Signed-off-by: ZhiqianXia <xzq0528@outlook.com>

2021-02-07 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2525) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2525) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=2525) it.</sub>

2021-02-08 18:13 UTC, greg-lunarg requested changes
Looks fine functionally. Just some cosmetic tweeks.

Has anyone filed issues against the original CTS code? It would be least disruptive to have those fixed before merging this.

2021-02-08 18:13 UTC, greg-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +		    error(loc, "cannot specify atomic counter with location","atomic","");
Can you please change message to "cannot specify on atomic counter"? Also, should we replace "atomic" token with "atomic_uint"? Finally, the indentation seems a little off here. Can you please fix?

2021-02-09 01:33 UTC, ZhiqianXia commented on glslang/MachineIndependent/ParseHelper.cpp
> +		    error(loc, "cannot specify atomic counter with location","atomic","");
@greg-lunarg Thank your commits. I think that  Message to " cannot specify on atomic counter " , token to " location " is better .  That would be more clear for user.

2021-02-11 17:33 UTC, greg-lunarg approved these changes
LGTM. Just waiting for CTS changes to merge.

2021-02-17 02:44 UTC, ZhiqianXia commented
@greg-lunarg thank you for review.

2021-02-22 01:37 UTC, ZhiqianXia commented
@greg-lunarg Hi greg , It seems not merged to the glslang repository. Could you help me on it ?

2021-02-23 00:36 UTC, merged