Fixed cmake generation warning for regeneration project build files.
KhronosGroup/glslang pull request #2537
Opened 2021-02-18 23:20 UTC by proydakov

Hi, GLSLANG Team.

Then I'm trying to regenerate project build files I see cmake warning.
As I see from kitware cmake main repo we should use 'cmake_minimum_version' before 'project' directive:

https://github.com/Kitware/CMake/blob/master/CMakeLists.txt

Could you verify and accept my changes, pls?

[BEFORE]:

% cmake ..
CMake Warning (dev) at CMakeLists.txt:35 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- No build type selected, default to Debug
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.9")
-- Found PythonInterp: /usr/local/bin/python3 (found suitable version "3.9", minimum required is "3")
-- optimizer enabled
-- Google Mock found - building tests
-- Configuring done

[AFTER]:

% cmake ..
-- No build type selected, default to Debug
-- Google Mock was not found - tests based on that will not build
-- Configuring done
-- Generating done

Best regards, Proydakov Evgeny

2021-02-20 15:10 UTC, proydakov commented
As I see all CI passed without problems. Is it possible to accept my PR, pls?

2021-02-22 20:49 UTC, greg-lunarg commented on CMakeLists.txt
>  # include a version of CMake >= 3.1
Can you please move these two comment lines above the cmake_minimum_required() command?

2021-02-22 20:52 UTC, greg-lunarg requested changes
Thank you for fixing this. Just a simple comment change is needed for check in.

2021-02-22 20:52 UTC, greg-lunarg commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8.12)
Can you please also move the two comment lines below to above the cmake_minimum_required() command? They go with this command.

2021-02-23 14:13 UTC, proydakov commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 2.8.12)
Yep.

2021-02-23 17:23 UTC, merged