TextureOffset not support sampler2DArrayShadow sampler until 430.
KhronosGroup/glslang pull request #2609
Opened 2021-04-14 13:30 UTC by ZhiqianXia

Hi ,
glslang should report an error about textureOffset , because textureOffset not support sampler2DArrayShadow sampler until 430.

shader

#version 300 es
precision mediump float;
in highp vec4 dEQP_Position;
uniform mediump sampler2DArrayShadow s;
void main()
{
                gl_Position = vec4(textureOffset(s, vec4(0), ivec2(0)));
                gl_Position = dEQP_Position;
}
Reference:

https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.20.pdf
https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.30.pdf

2021-04-14 20:49 UTC, greg-lunarg requested changes
Sorry, some additional improvements requested.

You can make the changes on your current local branch, squash to one commit with rebase -i HEAD~2, and then force push the branch with git push -f <your fork> <your branch>.

2021-04-14 20:49 UTC, greg-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +            if (callNode.getOp() == EOpTextureOffset && version <= 420) {
Sorry, but I just noticed this.

The logic would be cleaner and the error messaging more appropriate if the version test was removed here and done below.

2021-04-14 20:49 UTC, greg-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                    error(loc, "TextureOffset not support the sampler2DArrayShadow : ", "sampler",
Replace the error call here with the following logic:

if (isEsProfile())
    error(loc, "TextureOffset does not support sampler2DArrayShadow : ", "sampler", "ES Profile");
else if (version <= 420)
    error(loc, "TextureOffset does not support sampler2DArrayShadow : ", "sampler", "version <= 420");

2021-04-15 13:50 UTC, ZhiqianXia commented on glslang/MachineIndependent/ParseHelper.cpp
> +            if (callNode.getOp() == EOpTextureOffset && version <= 420) {
Thank your commits.

2021-04-19 15:48 UTC, greg-lunarg commented
I just pushed a commit onto your Feature2 branch. Your new test needed to be added to the master test list. And the compare file needed to be updated accordingly.

With this change, if it passes CI, all my concerns will be addressed and I can merge.

2021-04-19 15:49 UTC, greg-lunarg approved these changes
With my latest commit, this PR should be good to merge.

2021-04-19 18:03 UTC, merged

2021-04-23 03:09 UTC, ZhiqianXia commented
@greg-lunarg Thank you for your commit!