Added usage hint for --auto-sampled-textures and added test cases
KhronosGroup/glslang pull request #2621
Opened 2021-04-22 11:15 UTC by Rob2309

This PR adds the requested test cases and usage hints for #2616.

2021-04-22 17:04 UTC, greg-lunarg requested changes
One question about terminology. Otherwise good. Thanks for the submission!

2021-04-22 17:04 UTC, greg-lunarg commented on StandAlone/StandAlone.cpp
> +           "                                    existing textures to combined image-samplers\n"
...combined texture-samplers?

2021-04-22 17:11 UTC, Rob2309 commented on StandAlone/StandAlone.cpp
> +           "                                    existing textures to combined image-samplers\n"
Oops I used the Spirv terminology there, I could change this when I‘m home.

2021-04-23 16:50 UTC, greg-lunarg commented on StandAlone/StandAlone.cpp
> +           "                                    existing textures to combined image-samplers\n"
or even ...sampled textures :)

2021-04-27 14:06 UTC, Rob2309 commented on StandAlone/StandAlone.cpp
> +           "                                    existing textures to combined image-samplers\n"
done :)

2021-04-27 17:36 UTC, merged