remove unneeded extra constructions now that pool allocation is fixed
KhronosGroup/glslang pull request #2811
Opened 2021-11-11 02:22 UTC by mbechard

2021-11-13 00:20 UTC, greg-lunarg requested changes
Just need to touch up the comments to no longer refer to pool allocation issue. Otherwise good. Thanks!

2021-11-13 00:20 UTC, greg-lunarg commented on glslang/MachineIndependent/SymbolTable.cpp
>          // Extra constructions to make sure they use the correct allocator pool
Can you please fix this comment?

2021-11-13 00:20 UTC, greg-lunarg commented on glslang/MachineIndependent/SymbolTable.cpp
>          // Need to declare and assign so newS is using the correct pool allocator
Can you please fix this comment too?

2021-11-15 15:45 UTC, mbechard commented on glslang/MachineIndependent/SymbolTable.cpp
>          // Extra constructions to make sure they use the correct allocator pool
Done, sorry about that.

2021-11-17 23:05 UTC, greg-lunarg commented
@mbechard If you rebase your branch and re-push it, I think these failures will clear up.

2021-11-18 01:49 UTC, mbechard commented
Sorry, forgot recheck the PR to see if the build failed.

2021-11-18 17:18 UTC, merged