Vulkan rules relaxed for glslang C interface
KhronosGroup/glslang pull request #2836
Opened 2021-11-30 09:58 UTC by chaoticbob

Hi,

This PR adds Vulkan rules relaxed to the glslang C interface to make it more useful for Vulkan. I wasn't able to find a precedent for how this behavior should be added so I added a member variable to glslang_input_t. If this doesn't feel like a natural usage to the C interface I'm happy to make any adjustments. PTAL. 

Cheers,
Hai

2021-11-30 16:22 UTC, jeremy-lunarg approved these changes
LGTM

2021-11-30 18:28 UTC, greg-lunarg requested changes
While this would work, I think even better would be to add to the interface you created with your last PR (glslang_shader_set_options) and add this option along with the auto location and auto binding options.

The reason I would prefer that approach is that it would avoid changing the externally visible structure glslang_input_t which can "break" existing code using this interface.

Does this sound ok?

2021-12-01 00:37 UTC, chaoticbob commented
@greg-lunarg Yes, that makes sense. Will make the appropriate changes.

2021-12-01 08:59 UTC, chaoticbob commented
@greg-lunarg I made the changes per your suggestion. PTAL.

2021-12-01 17:27 UTC, greg-lunarg requested changes
I think just one problem, otherwise good.

2021-12-01 17:27 UTC, greg-lunarg commented on glslang/CInterface/glslang_c_interface.cpp
> +    if (options & GLSLANG_SHADER_AUTO_MAP_LOCATIONS) {
Cut and paste error?

2021-12-01 17:28 UTC, chaoticbob commented on glslang/CInterface/glslang_c_interface.cpp
> +    if (options & GLSLANG_SHADER_AUTO_MAP_LOCATIONS) {
Totally. This what I get for coding at 4AM. Will fix. Sorry.

2021-12-01 17:32 UTC, chaoticbob commented
@greg-lunarg Fixed the copy/paste error.

2021-12-01 17:38 UTC, greg-lunarg approved these changes
LGTM. Thanks for the code!

2021-12-07 23:12 UTC, merged