Added GLSL version override interface and CLI
KhronosGroup/glslang pull request #2851
Opened 2022-01-01 09:34 UTC by chaoticbob

PR to address question assekd in ##2850.

This change list allows a user to override the GLSL version from the
command line or through the C and C++ interfaces. This will override the
override happens in ProcessDeferred() before DeduceVersionProfile() so
the process should still error out if the version is insufficient for
the shader code.

- Added --glsl-version <version> to CLI.
- Added parameter to route glslVersion as override version to
  preprocessor and parse functions to C++ interface.
- Updated C interface with function to override GLSL version.

2022-01-05 18:42 UTC, greg-lunarg requested changes
The code looks fine.

It is common practice to add at least one test which indicates the capability is working to detect regressions. Functionality that involves command line options is often added into the Test/runtests script. Besides updating the script, you will just need to add a glsl shader to Test/ and an output file in Test/baseResults.

2022-01-06 17:33 UTC, chaoticbob commented
Hi Greg, thanks for the guidance. I will find a spot of time to make these changes.

2022-01-10 18:32 UTC, greg-lunarg requested changes
Thanks for the tests!

Sorry to ask for one more change, but could you change the original versions to 110 so that they will cause a failure if your new option is not enabled. Otherwise looks good.

2022-01-11 15:35 UTC, chaoticbob commented
Hi Greg, do you mean the versions in the shaders or in the StandAlone.cpp?

2022-01-11 17:32 UTC, greg-lunarg commented
> Hi Greg, do you mean the versions in the shaders or in the StandAlone.cpp?

In the shaders.

2022-03-24 22:43 UTC, greg-lunarg approved these changes
LGTM. Thanks for the code!

2022-03-24 23:51 UTC, merged