HLSL Instance attribute translated as spirv invocations attribute
KhronosGroup/glslang pull request #2948
Opened 2022-05-21 15:20 UTC by Gabriele91

Hi there! 

During my analysis of the MS's DXC behavior on the management of the attribute "instance" for the geometry shader, 
I saw a different result. In the DXC translation, it translated as 
```
OpExecutionMode %geometry Invocations <number>
```
Instead, in GLSlang, it is ignored (i.e. Invocations is always 1)
So, it is quite annoying, in many scenarios (e.g. CSM algorithm).

---

This is an example:
```HLSL
#define IVec2 int2
#define IVec3 int3
#define IVec4 int4
#define IMat3 int3x3
#define IMat4 int4x4
#define Vec2 float2
#define Vec3 float3
#define Vec4 float4
#define Mat3 float3x3
#define Mat4 float4x4
#define DVec2 double2
#define DVec3 double3
#define DVec4 double4
#define DMat3 double3x3
#define DMat4 double4x4
#define Sampler2D(name) SamplerState  name; Texture2D name ## _texture;
#define Sampler3D(name) SamplerState  name; Texture3D name ## _texture;
#define SamplerCube(name) SamplerState  name; TextureCube name ## _texture;
#define sample_texture(name,pos) name ## _texture.Sample(name,pos)

 #line 45
    struct VertexShaderInput
    {
        Vec3 m_position : POSITION;
        Vec3 m_color    : COLOR0;
    };
    
    struct VertexShaderOutput
    {
        Vec4 m_position : SV_POSITION;  // interpolated vertex position (system value)
        Vec4 m_color    : COLOR0;       // interpolated diffuse color
    };
    
    cbuffer Camera : register(b0)
    {
        Vec4 camera_viewport;
        Mat4 camera_projection;
        Mat4 camera_view;
        Mat4 camera_model;
        Vec3 camera_position;
    };
    
    cbuffer Transform : register(b1)
    {
        Mat4 model_model;
        Vec3 model_position;
        Vec3 model_scale;
        Mat3 model_rotation;
    };
    
    //global uniform
    float mask;
    Vec4 color;

    //texture
    Sampler2D(diffuse_texture);

    [maxvertexcount(3)]
    [instance(5)]
    void geometry(triangle VertexShaderOutput input[3]
			    , inout TriangleStream<VertexShaderOutput> output
	                    , uint id : SV_GSInstanceID)
    {
	    // for each triangle's vertices
	    [loop]
	    for (int i = 0; i < 3; ++i)
	    {
		    output.Append(input[i]);
	    }
	    output.RestartStrip();
    }
```

glslang output:
  
``` SPIRV
  WARNING: D:\local\Temp\8f60bf27-4962-4a11-9502-322a1e2da66e.hlsl:86: '' : attribute does not apply to entry point 

; SPIR-V
; Version: 1.3
; Generator: Khronos Glslang Reference Front End; 10
; Bound: 159
; Schema: 0
               OpCapability Geometry
          %1 = OpExtInstImport "GLSL.std.450"
               OpMemoryModel Logical GLSL450
               OpEntryPoint Geometry %geometry "geometry" %output_m_position %output_m_color %input_m_position %input_m_color %id
               OpExecutionMode %geometry Triangles
               OpExecutionMode %geometry Invocations 1
               OpExecutionMode %geometry OutputTriangleStrip
               OpExecutionMode %geometry OutputVertices 3
               OpSource HLSL 500
               OpName %geometry "geometry"
               OpName %VertexShaderOutput "VertexShaderOutput"
               OpMemberName %VertexShaderOutput 0 "m_position"
               OpMemberName %VertexShaderOutput 1 "m_color"
               OpName %output_m_position "output.m_position"
               OpName %output_m_color "output.m_color"
               OpName %input_m_position "input.m_position"
               OpName %input_m_color "input.m_color"
               OpName %id "id"
               OpName %param "param"
               OpDecorate %output_m_position BuiltIn Position
               OpDecorate %output_m_color Location 0
               OpDecorate %input_m_position BuiltIn Position
               OpDecorate %input_m_color Location 0
               OpDecorate %id BuiltIn InvocationId
       %void = OpTypeVoid
          %3 = OpTypeFunction %void
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%VertexShaderOutput = OpTypeStruct %v4float %v4float
       %uint = OpTypeInt 32 0
     %uint_3 = OpConstant %uint 3
%_arr_VertexShaderOutput_uint_3 = OpTypeArray %VertexShaderOutput %uint_3
%_ptr_Function__arr_VertexShaderOutput_uint_3 = OpTypePointer Function %_arr_VertexShaderOutput_uint_3
%_ptr_Function_VertexShaderOutput = OpTypePointer Function %VertexShaderOutput
        %int = OpTypeInt 32 1
      %int_0 = OpConstant %int 0
      %int_3 = OpConstant %int 3
       %bool = OpTypeBool
%_ptr_Output_v4float = OpTypePointer Output %v4float
%output_m_position = OpVariable %_ptr_Output_v4float Output
%output_m_color = OpVariable %_ptr_Output_v4float Output
      %int_1 = OpConstant %int 1
%_arr_v4float_uint_3 = OpTypeArray %v4float %uint_3
%_ptr_Input__arr_v4float_uint_3 = OpTypePointer Input %_arr_v4float_uint_3
%input_m_position = OpVariable %_ptr_Input__arr_v4float_uint_3 Input
%_ptr_Input_v4float = OpTypePointer Input %v4float
%input_m_color = OpVariable %_ptr_Input__arr_v4float_uint_3 Input
      %int_2 = OpConstant %int 2
%_ptr_Input_uint = OpTypePointer Input %uint
         %id = OpVariable %_ptr_Input_uint Input
   %geometry = OpFunction %void None %3
          %5 = OpLabel
      %param = OpVariable %_ptr_Function__arr_VertexShaderOutput_uint_3 Function
         %54 = OpAccessChain %_ptr_Input_v4float %input_m_position %int_0
         %55 = OpLoad %v4float %54
         %58 = OpAccessChain %_ptr_Input_v4float %input_m_color %int_0
         %59 = OpLoad %v4float %58
         %61 = OpAccessChain %_ptr_Input_v4float %input_m_position %int_1
         %62 = OpLoad %v4float %61
         %64 = OpAccessChain %_ptr_Input_v4float %input_m_color %int_1
         %65 = OpLoad %v4float %64
         %68 = OpAccessChain %_ptr_Input_v4float %input_m_position %int_2
         %69 = OpLoad %v4float %68
         %71 = OpAccessChain %_ptr_Input_v4float %input_m_color %int_2
         %72 = OpLoad %v4float %71
        %156 = OpCompositeConstruct %VertexShaderOutput %69 %72
        %151 = OpCompositeConstruct %VertexShaderOutput %62 %65
        %146 = OpCompositeConstruct %VertexShaderOutput %55 %59
        %139 = OpCompositeConstruct %_arr_VertexShaderOutput_uint_3 %146 %151 %156
               OpStore %param %139
               OpBranch %107
        %107 = OpLabel
        %158 = OpPhi %int %int_0 %5 %121 %111
        %110 = OpSLessThan %bool %158 %int_3
               OpLoopMerge %122 %111 DontUnroll
               OpBranchConditional %110 %111 %122
        %111 = OpLabel
        %113 = OpAccessChain %_ptr_Function_VertexShaderOutput %param %158
        %114 = OpLoad %VertexShaderOutput %113
        %125 = OpCompositeExtract %v4float %114 0
        %126 = OpCompositeExtract %v4float %114 1
               OpStore %output_m_position %125
               OpStore %output_m_color %126
               OpEmitVertex
        %121 = OpIAdd %int %158 %int_1
               OpBranch %107
        %122 = OpLabel
               OpEndPrimitive
               OpReturn
               OpFunctionEnd
  ```
  
  DXC output:
  ```SPIRV
  ; SPIR-V
; Version: 1.0
; Generator: Google spiregg; 0
; Bound: 50
; Schema: 0
               OpCapability Geometry
               OpMemoryModel Logical GLSL450
               OpEntryPoint Geometry %geometry "geometry" %gl_Position %in_var_COLOR0 %gl_InvocationID %gl_Position_0 %out_var_COLOR0
               OpExecutionMode %geometry OutputVertices 3
               OpExecutionMode %geometry Invocations 5
               OpExecutionMode %geometry Triangles
               OpExecutionMode %geometry OutputTriangleStrip
               OpSource HLSL 600
               OpName %in_var_COLOR0 "in.var.COLOR0"
               OpName %out_var_COLOR0 "out.var.COLOR0"
               OpName %geometry "geometry"
               OpName %VertexShaderOutput "VertexShaderOutput"
               OpMemberName %VertexShaderOutput 0 "m_position"
               OpMemberName %VertexShaderOutput 1 "m_color"
               OpName %param_var_input "param.var.input"
               OpDecorate %gl_Position BuiltIn Position
               OpDecorate %gl_InvocationID BuiltIn Inv [...]

2022-05-21 15:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2948) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2948) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=2948) it.</sub>

2022-05-23 18:06 UTC, greg-lunarg requested changes
Can you please add a regression test based on the shader you provided? See all the tests in the Test/ subdirectory. Otherwise LGTM.

2022-05-23 18:22 UTC, Gabriele91 commented
> Can you please add a regression test based on the shader you provided? See all the tests in the Test/ subdirectory. Otherwise LGTM.

Hi Greg Fischer. 

Sure! 
I'm going to do it, but give me just three/four days (I can do it just in my free time).

2022-05-24 18:14 UTC, Gabriele91 commented
My apologies, I forgot the shader output.
Now, it has to work!
![image](https://user-images.githubusercontent.com/641004/170103789-614f4467-795f-44c7-849f-68dd24274d38.png)
![image](https://user-images.githubusercontent.com/641004/170104106-04522ef4-49bb-4d6b-bd1c-39e62c645d20.png)

2022-05-24 20:11 UTC, merged