Remove the unused `OS_CleanupThreadData`
KhronosGroup/glslang pull request #2997
Opened 2022-08-11 11:53 UTC by RandomShaper

I was building glslang for a platform that doesn't support `PTHREAD_CANCEL_ENABLE` and during the investigation about what it was being used for I realized that its only use belongs in an unused function — `OS_CleanupThreadData`.

2022-08-11 11:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2997) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=2997) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=2997) it.</sub>

2022-08-26 17:37 UTC, greg-lunarg requested changes
You will also need to remove DetachThreadLinux() in Unix/ossource.cpp. That is the reason for the one CI failure.

Please also remove the Thread cleanup comment above it.

2022-08-26 19:14 UTC, RandomShaper commented
Done.

2022-08-31 22:49 UTC, jeremy-lunarg approved these changes
LGTM. I don't think these functions are publicly supported.

2022-08-31 23:24 UTC, greg-lunarg approved these changes

2022-08-31 23:25 UTC, merged