Add support for GL_NV_shader_invocation_reorder.
KhronosGroup/glslang pull request #3054
Opened 2022-10-31 21:30 UTC by alelenv

GLSL spec : https://github.com/KhronosGroup/GLSL/pull/196
SPV spec : https://github.com/KhronosGroup/GLSL/pull/196
Headers : https://github.com/KhronosGroup/SPIRV-Headers/pull/300

2022-11-21 20:27 UTC, alelenv commented
@greg-lunarg or @johnkslang : Headers and spec are merged. Waiting for tools to be merged so I can flip the known_good

Can you start reviewing in the meantime?

Thanks

2022-12-01 20:37 UTC, alelenv commented
Repinging @greg-lunarg and @johnkslang 

All bots are green
Please start reviewing

Thanks

2022-12-06 00:01 UTC, dgkoch commented
@jeremy-lunarg can you help review / merge this?

2022-12-09 17:49 UTC, greg-lunarg commented
Sorry for the delay. Looking now.

2022-12-09 18:31 UTC, greg-lunarg requested changes
Please fix Android-ndk build issue.

2022-12-09 18:37 UTC, greg-lunarg commented on SPIRV/GlslangToSpv.cpp
> +                  builder.getStorageClass(id) == spv::StorageClassHitObjectAttributeNV)) {
It looks like this will also fix the clang-ubuntu build issue.

2022-12-09 19:17 UTC, greg-lunarg approved these changes
LGTM. Thanks for the code!

2022-12-09 20:19 UTC, merged