Shaochi/bindless
KhronosGroup/glslang pull request #3066
Opened 2022-11-15 16:12 UTC by ShchchowAMD

Add support for ARB_bindless_texture.

There's still some features related to non_uniform. Would update soon.

2022-11-15 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3066) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3066) before we can accept your contribution.<br/><hr/>**Zhou** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3066) it.</sub>

2022-11-29 01:15 UTC, greg-lunarg commented
Can you please add tests for this functionality?

This can be done by adding shaders that use ARB_bindless_texture to the Test/ directory. You will also need to add the files to AST.FromFile.cpp. See switch.frag as an example.

You will also need to create result files in Test/baseResults/, but this can be done by building and running build/gtests/Release/glslangtests.exe --update-mode.

2022-11-29 09:53 UTC, ShchchowAMD commented
> 

Thanks for reminding. I'll update test and out file here.

2022-11-29 18:36 UTC, greg-lunarg requested changes
Thanks for the test. Does your code support the full extension? If so, could we get tests for the other salient shader changes? Eg, from the extension spec:

`In particular, sampler and image types may be used as shader inputs/outputs, temporary variables, and uniform block members, and may be assigned to by shader code.`

Also, could we get an error message when this extension is used when targeting SPIR-V. For example, when compiled with this command line:

`glslangValidator.exe -V --target-env vulkan1.2 --amb --aml -o t.frag.spv t.frag`

The error would just say that this extension is not currently supported when targeting SPIR-V.

2022-11-29 18:36 UTC, greg-lunarg commented on glslang/MachineIndependent/Versions.cpp
> +    extensionBehavior[E_GL_ARB_bindless_texture]          = EBhDisable;
Indentation

2022-11-29 18:36 UTC, greg-lunarg commented on glslang/MachineIndependent/Versions.h
> +const char* const E_GL_ARB_bindless_texture          = "GL_ARB_bindless_texture";
Indentation

2022-11-30 01:48 UTC, ShchchowAMD commented
Thanks, I'll make another PR today.

2022-11-30 08:03 UTC, ShchchowAMD commented on glslang/MachineIndependent/Versions.cpp
> +    extensionBehavior[E_GL_ARB_bindless_texture]          = EBhDisable;
Fixed.

2022-11-30 08:03 UTC, ShchchowAMD commented on glslang/MachineIndependent/Versions.h
> +const char* const E_GL_ARB_bindless_texture          = "GL_ARB_bindless_texture";
Fixed.

2022-11-30 08:08 UTC, ShchchowAMD commented
> Thanks for the test. Does your code support the full extension? If so, could we get tests for the other salient shader changes? Eg, from the extension spec:
> 
> `In particular, sampler and image types may be used as shader inputs/outputs, temporary variables, and uniform block members, and may be assigned to by shader code.`
> 
> Also, could we get an error message when this extension is used when targeting SPIR-V. For example, when compiled with this command line:
> 
> `glslangValidator.exe -V --target-env vulkan1.2 --amb --aml -o t.frag.spv t.frag`
> 
> The error would just say that this extension is not currently supported when targeting SPIR-V.

Hi greg, thanks for reply. I've made another PR according to your reviews.

For tip2, I don't make sure whether I understand right, so just double check:

SPIR-V already has disassembled extension keyword:

`OpSourceExtension "GL_ARB_bindless_texture"`

So what we need to do is to disable usage of extension when generate SPV targeting vulkan?

Current glslang have checks to require spv version and vulkan, I add another check to allow some extensions reserved for vk in the latest PR.

Thanks for your review again.

2022-12-02 19:21 UTC, greg-lunarg commented
Thank you for the error check, although I would like one additional small change :)

Can you please disallow for ALL SPIR-V, generating for OpenGL as well as Vulkan?

Specifically, could you change the name of the variable vkReservedExt to spvUnsupportedExt?

Also check instead spvVersion.spv and change Vulkan to SPIR-V in the error message?

2022-12-07 05:30 UTC, ShchchowAMD commented
> 

Thanks for detailed suggestion. I've disabled it for spv and changed codes according to your comment.

2022-12-07 21:31 UTC, greg-lunarg approved these changes
LGTM. Thanks!

2022-12-07 21:38 UTC, greg-lunarg approved these changes
LGTM. Thanks!

2022-12-07 21:38 UTC, merged