[glslang] Refine implicit array size interfaces.
KhronosGroup/glslang pull request #3074
Opened 2022-11-25 06:22 UTC by ShchchowAMD

Help to check builtin and other variables if across stages.

2022-11-29 21:48 UTC, greg-lunarg commented
Can you please add tests that demonstrate the new functionality? Similar to #3066, although I think you will instead register in Link.FromFile.cpp.

2022-11-30 01:48 UTC, ShchchowAMD commented
Thanks for reminding. I'll add test for this one and also future PRs.

2022-12-01 09:16 UTC, ShchchowAMD commented
> Can you please add tests that demonstrate the new functionality? Similar to #3066, although I think you will instead register in Link.FromFile.cpp.

Add tests for link time error check.

2022-12-08 20:49 UTC, greg-lunarg commented on glslang/MachineIndependent/linkValidate.cpp
> +                        error(infoSink, "Implicit size of unsized array aren't match same symbol among multiple shaders.");
"aren't" -> "doesn't"

2022-12-08 20:50 UTC, greg-lunarg commented on glslang/MachineIndependent/linkValidate.cpp
> -                    symbol->getQualifier().layoutLocation = unitSymbol->getQualifier().layoutLocation;
Did you mean to remove this? If so, why?

2022-12-11 13:04 UTC, ShchchowAMD commented on glslang/MachineIndependent/linkValidate.cpp
> +                    error(infoSink, "Not all provided sizes match across all geometry shaders in the program");
Yes, I'll fix it.

2022-12-11 13:04 UTC, ShchchowAMD commented on glslang/MachineIndependent/linkValidate.cpp
> +                        error(infoSink, "Implicit size of unsized array aren't match same symbol among multiple shaders.");
Thanks, will fix in next commit.

2022-12-11 13:05 UTC, ShchchowAMD commented on glslang/MachineIndependent/linkValidate.cpp
> -                    symbol->getQualifier().layoutLocation = unitSymbol->getQualifier().layoutLocation;
Sorry, this is a mistake via merging codes, I'll add this block back.

2022-12-11 14:00 UTC, ShchchowAMD commented
Add a fix for corner case:
when a builtin variable is used across stages, set initialized implicit size to 0.

If stage A uses it by implicitly indexing but not in stage B, it should not report an error.

This is especially for vars in gl_PerVertex and other built-in blocks available across stages.

The main idea is to use implicitSize == 0 to determine whether a declared unsized array has been visited with an index.

For example:

VS:

...
void c(vec4 p, vec4 c[8], uint x)
{
	gl_ClipDistance[7] = mix(1.0, dot(p, c[7]), x(c, 7u));
}
...
void main() {
  ...
  c(...)
}


GS (CLIP not defined):

...
#if defined(CLIP)
void o(uint i)
{
	gl_ClipDistance[7] = gl_in[i].gl_ClipDistance[7];
}
#endif
...
void main(){
  ...
  #if defined(CLIP)
	  o(0u);
  #endif
  ...
}

2022-12-12 02:36 UTC, ShchchowAMD commented
Test info should be changed.
Latest added commit for default set implicit sized check needs a test for it.
I'll add a new commit today.

2022-12-12 18:39 UTC, greg-lunarg requested changes
Just one small change that got missed. Thanks for your persistence!

2022-12-12 18:39 UTC, greg-lunarg commented on glslang/MachineIndependent/linkValidate.cpp
> +                        error(infoSink, "Implicit size of unsized array aren't match same symbol among multiple shaders.");
aren't -> doesn't :)

Also in the .out file. Thanks!

2022-12-13 01:39 UTC, ShchchowAMD commented on glslang/MachineIndependent/linkValidate.cpp
> +                        error(infoSink, "Implicit size of unsized array aren't match same symbol among multiple shaders.");
Sorry, I forgot this one :)
New commit has fixed this error message.

2022-12-13 18:18 UTC, greg-lunarg approved these changes
LGTM. Thanks for the code!

2022-12-13 18:20 UTC, merged