[glslang] Add impl for several matrix and constant op.
KhronosGroup/glslang pull request #3082
Opened 2022-12-07 07:53 UTC by ShchchowAMD

Add impl for some ops, mainly for matrix and float / conv ops.

Finished op List:
(all of them have already been added to symbol table and related to a built-in op/function before, but not actually be implemented yet.)

```
EOpMatrixInverse
EOpTranspose
EOpPackSnorm2x16
EOpPackUnorm2x16
EOpPackHalf2x16
EOpUnpackSnorm2x16
EOpUnpackUnorm2x16
EOpUnpackHalf2x16
EOpDeterminant
EOpSinh
EOpCosh
EOpTanh
EOpAsinh
EOpAcosh
EOpAtanh
EOpFloatBitsToInt
EOpFloatBitsToUint
EOpIntBitsToFloat
EOpUintBitsToFloat
EOpDoubleBitsToInt64
EOpDoubleBitsToUint64
EOpInt64BitsToDouble
EOpUint64BitsToDouble
EOpMul (matrixCompMult)
EOpComma
```

2022-12-15 19:08 UTC, greg-lunarg requested changes

2022-12-15 19:08 UTC, greg-lunarg commented on glslang/MachineIndependent/Constant.cpp
> +#include "../../SPIRV/hex_float.h"
This is a little ugly. The MachineIndependent module should be independent of any target module such as SPIRV.

There really is nothing about hex_float.h (and bitutils.h) that is related to SPIRV. They were brought in to support SPIRV and that is why they were placed there. They do have a spvutils namespace, but that is it.

How much work would it be to move these files into MachineIndependent and remove any reference of SPIRV from them?

2022-12-16 10:21 UTC, ShchchowAMD commented on glslang/MachineIndependent/Constant.cpp
> +#include "../../SPIRV/hex_float.h"
Yes, you are right.

The reason to include hex_float here is to keep those float/bit ops following same rules/implementation.

I'd have a try to refine the folder structure and namespace locally first.

2023-05-25 23:06 UTC, arcady-lunarg commented
@ShchchowAMD do you intend to get back to this at some point?

2023-05-28 07:00 UTC, ShchchowAMD commented
> 

Thanks for reminding. I'll make a commit recently to fix issue discussed above.

2025-06-26 20:21 UTC, dnovillo commented
@ShchchowAMD same question. Are you still interested in this PR?

2026-07-16 17:29 UTC, dnovillo commented
@ShchchowAMD we've gotten no response to this in more than a year. I'll close it for now. Please re-open if you are still interested in this.

2026-07-16 17:29 UTC, closed without merging