change HLSL/hlslParseables.cpp to support InterlockedAdd on F=float types
KhronosGroup/glslang pull request #3134
Opened 2023-02-04 09:48 UTC by rcoreilly

This enables use of `InterlockedAdd` on float types per this extension: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_shader_atomic_float.html

It has been tested and produces the expected results, generating an `atomicAdd` opcode.

2023-02-04 09:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3134) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3134) it.</sub>

2023-02-06 17:27 UTC, arcady-lunarg requested changes
Thanks for the patch. Could you add some tests to verify that the expected results are produced? It should just be a matter of adding tests for InterlockedAdd with floats to `Test/hlsl.intrinsics.comp` and then updating the base results using `build/gtests/Release/glslangtests.exe --update-mode`.

2023-02-08 10:02 UTC, rcoreilly commented
ok did that..

2023-02-08 20:28 UTC, arcady-lunarg approved these changes
LGTM, thanks for adding the test.

2023-02-08 20:28 UTC, merged