[extension] the GL_QCOM_image_processing support
KhronosGroup/glslang pull request #3191
Opened 2023-04-18 18:07 UTC by wooyoungqcom

The corresponding GLSL spec is here: 
https://github.com/KhronosGroup/GLSL/blob/master/extensions/qcom/GLSL_QCOM_image_processing.txt

2023-04-18 18:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3191) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3191) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3191) it.</sub>

2023-04-20 16:49 UTC, arcady-lunarg requested changes
You need to add the new capabilities to Doc.cpp, otherwise this looks good.

2023-04-20 21:35 UTC, wooyoungqcom commented on Test/baseResults/spv.tpipBlockMatchSAD.frag.out
> +                              Capability Bad
Thank you so much,.
The branch updated.

2023-04-20 23:23 UTC, wooyoungqcom commented on Test/baseResults/spv.tpipBlockMatchSAD.frag.out
> +                              Capability Bad
It seems I forgot to update the .out files.

2023-04-20 23:47 UTC, wooyoungqcom commented on Test/baseResults/spv.tpipBlockMatchSAD.frag.out
> +                              Capability Bad
uploaded the updated .out files

2023-04-21 17:43 UTC, arcady-lunarg commented
Seems like CI is still failing, the SPIR-V result files say "Validation failed" while the ones in your patch don't (as they shouldn't). Is there a change in spirv-tools that this depends on? If so you'll also need to update the version of those in known_good.json.

2023-04-21 19:42 UTC, wooyoungqcom commented
Thank you so much, yes, I think spirv-val need get updated and we are planning to upstream the corresponding changes once the glslang changes are merged.  

It seems known_good.json contains the spirv-tools commit ID that the glslang testing should use. What is the process to follow ? (I am new to the process). Do we need to upstream the spirv-tools changes first before trying to merge the glslang changes ?

2023-07-18 21:33 UTC, arcady-lunarg commented
For reference, the spirv-tools pull request is https://github.com/KhronosGroup/SPIRV-Tools/pull/5223

2023-08-16 07:44 UTC, closed without merging