Fix building on OpenBSD when building shared libs
KhronosGroup/glslang pull request #3193
Opened 2023-04-19 02:36 UTC by brad0

OpenBSD does not link shared libs against libc so it is expected that the use of --no-undefined when linking will fail.

2023-04-19 02:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3193) it.</sub>

2023-04-21 19:25 UTC, arcady-lunarg requested changes
Since you're already touching this code, would you mind deleting the CMAKE_VERSION checks since we already require a minimum cmake version of 3.14?

2023-04-21 20:09 UTC, brad0 commented
Sure. Will do.

2023-04-22 00:51 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-04-22 00:51 UTC, merged