Add support for GL_EXT_shader_tile_image
KhronosGroup/glslang pull request #3197
Opened 2023-04-24 09:42 UTC by janharaldfredriksen-arm

Adds glslang support for GL_EXT_shader_tile_image - see https://github.com/KhronosGroup/GLSL/pull/203

2023-04-24 09:50 UTC, janharaldfredriksen-arm commented
I had one issue when regenerating the grammar.

In glslang/MachineIndependent/glslang_tab.cpp, the first token got generated as "$end" rather than "end of file". This causes a couple of tests to fail in regression because the expected error messages assume "end of file".

I've manually modified the file like so:
```
-  "$end", "error", "$undefined", "CONST", "BOOL", "INT", "UINT", "FLOAT",
+  "\"end of file\"", "error", "$undefined", "CONST", "BOOL", "INT", "UINT", "FLOAT",
```
But obviously that's not great... Other suggestions welcome.

(The version of Bison I had was slightly older than what was used before, but I don't know if that's got anything to do with it. At least I couldn't find anything obvious in documentation.)

2023-04-25 21:06 UTC, arcady-lunarg commented
The version of bison is in fact exactly the issue here, there was a change in 3.6 that changed the cryptically $end token to "end of file". If you could try regenerating the file using a newer bison, ideally 3.7.4 or later, it should work properly and is a better idea than tweaking the file by hand.

2023-04-27 11:34 UTC, janharaldfredriksen-arm commented
Worked better with bison 3.7.4.

Any idea what's up with the Windows CI?
Log says:
>ERROR: C:/users/containeradministrator/_bazel_containeradministrator/rtpovv7a/external/com_google_googletest/BUILD.bazel:57:1: C++ compilation of rule '@com_google_googletest//:gtest' failed (Exit 1)

2023-04-27 15:03 UTC, arcady-lunarg commented
The windows CI issue is a known problem due the required Visual Studio version being increased, I wouldn't worry about it. I'll take a look at your changes today.

2023-05-01 22:40 UTC, arcady-lunarg commented
I'm still reading through the code, but in the meantime one piece of feedback. I want to thank you for writing tests, but one think I think would be good to have in addition to the negative tests for the error cases is a positive test that actually generates some SPIR-V.

2023-05-03 19:29 UTC, arcady-lunarg requested changes
Looks good but I have some questions about ABI issues with new enum variants, and I would like to see a test that generates actually generates some SPIR-V using the extension.

2023-05-08 01:14 UTC, janharaldfredriksen-arm commented on glslang/MachineIndependent/Initialize.cpp
> -#endif
Good catch. A rebase bug, I think.

2023-05-08 02:51 UTC, janharaldfredriksen-arm commented
> Looks good but I have some questions about ABI issues with new enum variants, and I would like to see a test that generates actually generates some SPIR-V using the extension.

Added a couple of positive tests in the latest commit.

2023-05-08 20:10 UTC, arcady-lunarg reviewed
LGTM, but the PR needs to be rebased because another PR touching the enums got merged first.

2023-05-09 01:16 UTC, arcady-lunarg approved these changes
Thanks, LGTM, I'll merge it as soon as the CI finishes.

2023-05-09 01:49 UTC, merged

2024-04-25 22:59 UTC, arcady-lunarg commented
Turns out this was not in fact fine, you access `TIntermediate::usedIo[4]` when said array only has size 4 so it clobbers whatever follows it in the struct. And despite being enabled a while ago, ASAN didn't catch this bug until someone changed the size of `TIoRange`.

2024-04-25 22:59 UTC, arcady-lunarg commented
> Turns out this was not in fact fine, you access `TIntermediate::usedIo[4]` when said array only has size 4 so it clobbers whatever follows it in the struct. And despite being enabled a while ago, ASAN didn't catch this bug until someone changed the size of `TIoRange`. Goes to show that I need to review much more carefully in the future.