GL_EXT_ray_tracing_position_fetch
KhronosGroup/glslang pull request #3201
Opened 2023-04-28 16:19 UTC by ewerness-nv

2023-05-02 22:35 UTC, arcady-lunarg requested changes
The code changes look good aside from the issues with line endings and the new enum variants needing to come at the end in the public header files.

2023-05-02 22:35 UTC, arcady-lunarg commented on SPIRV/spirv.hpp
Looks like your patch switches the line endings for the whole file. Please try to stick with the existing unix-style line endings.

2023-05-02 22:35 UTC, arcady-lunarg commented on glslang/Include/BaseTypes.h
> +    EbvPositionFetch,
Since this file is part of the public interface of glslang, new enumeration values should be added at the end.

2023-05-02 22:35 UTC, arcady-lunarg commented on glslang/Include/intermediate.h
> +    EOpRayQueryGetIntersectionTriangleVertexPositionsEXT,
Since this file is part of the public interface of glslang, new enumeration values should be added at the end.

2023-05-05 03:01 UTC, dgkoch commented
@arcady-lunarg please re-review

2023-05-05 15:12 UTC, arcady-lunarg approved these changes
LGTM

2023-05-05 15:12 UTC, merged