`spirv-remap`: Output to single directory or one or more files
KhronosGroup/glslang pull request #3216
Opened 2023-05-08 15:29 UTC by allanmac

The `spirv-remap` tool currently outputs shaders to a single directory.

This can complicate integration with build systems that explicitly track both inputs and outputs produced by an executable.

The `spirv-remap` tool should support:
  * Outputting one or more inputs to a single directory -- the current behavior.
  * One output file per input -- new behavior.

This new behavior can be robustified using
`std::filesystem::is_directory()`.

2023-05-08 15:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3216) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3216) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3216) it.</sub>

2023-05-08 15:55 UTC, allanmac commented
Why do Bazel builds use `"-std=c++11"` instead of C++17?

2023-05-19 17:36 UTC, arcady-lunarg commented
I'm going to take a look at this today.

2023-05-19 19:43 UTC, arcady-lunarg commented
Actually, rather than adding the ifdefs for c++17, I'd like to switch everything to using c++17 first. I opened #3230 for that, once that is merged you can rebase your change on it.

2023-05-22 18:55 UTC, arcady-lunarg requested changes
@allanmac given that #3230 has been merged, could you rework this to remove the ifdefs for C++17? That's the officially required minimum version of C++ per the README anyway.

2023-05-22 19:29 UTC, allanmac commented
Yes, I will rework now that C++17 is universal.

2023-05-22 21:33 UTC, allanmac commented
If I'm reading it correctly, MSVC has supported C++17 (and `<filesystem>`) since VS 2017 15.7 using the `/std:c++17` switch.

Is this another example of a missing C++17 switch? 

---

This is the error I'm seeing in CI:

`CI-windows-msvc-2019-release-bazel — CI build failed`:

```
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\filesystem(13): warning STL4038: The contents of <filesystem> are available only with C++17 or later.
StandAlone/spirv-remap.cpp(394): error C2039: 'filesystem': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\algorithm(116): note: see declaration of 'std'
StandAlone/spirv-remap.cpp(394): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
StandAlone/spirv-remap.cpp(394): error C2039: 'is_directory': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\include\algorithm(116): note: see declaration of 'std'
StandAlone/spirv-remap.cpp(394): error C3861: 'is_directory': identifier not found
```

2023-05-22 22:40 UTC, arcady-lunarg commented
I think I missed some compiler flags for windows in the bazel build. I'll try to add those flags to force c++17 mode in that case.

2023-06-06 13:50 UTC, allanmac reviewed
Removed C++2017 dependency.

2023-06-27 18:28 UTC, arcady-lunarg commented
Sorry this has been taking so long to get merged, it turns out our android CI build was not up to standards and needs to be reworked a bit, so that C++17 works there as well. However, that is now on my todo list, and once that's in, we can rebase this PR and merge it.

2023-07-27 16:53 UTC, arcady-lunarg requested changes
The basic design of this is solid, though I haven't tested it yet. However, could you please make sure your new code follows the formatting conventions of the existing code?

2023-07-27 16:53 UTC, arcady-lunarg commented on StandAlone/spirv-remap.cpp
> +        {
In this case, I would omit the braces entirely.

2023-07-27 20:35 UTC, allanmac commented on StandAlone/spirv-remap.cpp
> +                std::vector<SpvWord> spv;
Done.

2023-07-27 20:36 UTC, allanmac commented on StandAlone/spirv-remap.cpp
> +            << " --input | -i file1 [file2...] --output | -o destdir | destfile1 [destfile2...]"
ACK

2023-07-27 20:37 UTC, allanmac commented on StandAlone/spirv-remap.cpp
> +                else
Whoops, done.

2023-07-27 20:37 UTC, allanmac commented on StandAlone/spirv-remap.cpp
> +        {
ACK/Done.

2023-07-28 16:11 UTC, arcady-lunarg approved these changes
LGTM

2023-07-28 16:13 UTC, merged