Spirv_intrinsics: Add support of type specifier to spirv_type
KhronosGroup/glslang pull request #3253
Opened 2023-07-02 15:43 UTC by amdrexu

Previously, spirv_type doesn't accept type specifier as its parameter. With this change, we can input non-array type specifier. This is because some SPIR-V type definition intructions often need to reference other SPIR-V types as its source operands. We add the support to facilitate such usage.

2023-07-06 21:29 UTC, arcady-lunarg requested changes
On the whole this is fine other than some unrelated whitespace changes that I would prefer you remove. While it would be nice to use std::variant here, I am fine doing that myself in a follow-up change.

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/Include/SpirvIntrinsics.h
> +    const TType* type;                    // Type specifier
This feels like an opportunity to use something like std::variant from C++17, now that we require C++17 as a minimum, but I can do that refactor in a followup change.

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/Include/SpirvIntrinsics.h
> +    TMap<int, TVector<const TIntermTyped*>> modeIds;
Could you remove these unrelated whitespace diffs?

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/Include/SpirvIntrinsics.h
> +    TMap<int, TVector<const TIntermConstantUnion*>> decorates;
Unrelated whitespace diff.

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/Include/SpirvIntrinsics.h
> +    TMap<int, TVector<const TIntermConstantUnion*>> decorateStrings;
Unrelated whitespace diff.

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/MachineIndependent/SpirvIntrinsics.cpp
> -        assert(constant);
This assert is already useless due to the if's condition dereferencing constant. Might it make sense to move it up to the top of the function instead?

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/MachineIndependent/SpirvIntrinsics.cpp
> +                                                             const TIntermConstantUnion* constant)
Unrelated whitespace change

2023-07-06 21:29 UTC, arcady-lunarg commented on glslang/MachineIndependent/SpirvIntrinsics.cpp
> +    if (constant->getBasicType() != EbtFloat && constant->getBasicType() != EbtInt &&
Unrelated whitespace diff.

2023-07-11 15:59 UTC, arcady-lunarg approved these changes
I did the whitespace fixes myself and updated your branch.

2023-07-11 17:26 UTC, merged

2023-07-13 14:58 UTC, amdrexu commented
> I did the whitespace fixes myself and updated your branch.

Thank you for your kind help. I take leaves and didn't notice the review comments :)