HLSL: Possibility to represent variable in binary form
KhronosGroup/glslang pull request #3259
Opened 2023-07-12 10:56 UTC by Dawid-Lorenz-Mobica

Fix for Issues: https://github.com/KhronosGroup/glslang/issues/3089

2023-07-12 18:21 UTC, arcady-lunarg requested changes
Looks okay overall, aside from a couple issues mentioned on specific lines, and one major one: this also adds support for binary literals to GLSL, which is not actually a thing that GLSL supports. You need to add a check to make sure that we're not compiling GLSL and to bail out early in that case. I would also like to see tests for the error cases here, both the "literal too big/too long" error messages and that this doesn't work with GLSL. There should be existing "negative" test files to which you can add some new cases.

2023-07-12 18:21 UTC, arcady-lunarg commented on Test/hlsl.conditional.frag
> +float2 fbSelect(bool2 cnd, float2 src0, float2 src1)
This looks like a line-ending diff, please revert.

2023-07-12 18:21 UTC, arcady-lunarg commented on Test/hlsl.conditional.frag
> +float4 c4;
This looks like a line-ending diff, please revert.

2023-07-12 18:21 UTC, arcady-lunarg commented on glslang/MachineIndependent/preprocessor/PpScanner.cpp
> +                        if (len < MaxTokenLength && ival <= 0x0fffffffffffffffull) {
Why 0x0fffffffffffffffull and not 0x7fffffffffffffffull?

2023-07-13 11:07 UTC, Dawid-Lorenz-Mobica commented on Test/hlsl.conditional.frag
> +float2 fbSelect(bool2 cnd, float2 src0, float2 src1)
Done.

2023-07-13 11:07 UTC, Dawid-Lorenz-Mobica commented on Test/hlsl.conditional.frag
> +float4 c4;
Done.

2023-07-13 11:07 UTC, Dawid-Lorenz-Mobica commented on glslang/MachineIndependent/preprocessor/PpScanner.cpp
> +                        if (len < MaxTokenLength && ival <= 0x0fffffffffffffffull) {
Yes, Right. I did copy-paste from the hexadecimal option

2023-07-17 20:53 UTC, arcady-lunarg requested changes
The code itself looks fine now, just one issue with your change to a test causing it to no longer generate SPIR-V code where it had previously done so. I think you need to move the negative tests to a different file, possibly a new test file.

2023-07-17 20:53 UTC, arcady-lunarg commented on Test/baseResults/hlsl.numericsuffixes.frag.out
> +SPIR-V is not generated for failed compile or link
I don't like that this changes the test to no longer generate any SPIR-V. Could you move the error cases to a separate file so that SPIR-V is still generated here?

2023-07-18 08:12 UTC, Dawid-Lorenz-Mobica commented on Test/baseResults/hlsl.numericsuffixes.frag.out
> +SPIR-V is not generated for failed compile or link
Done.

2023-07-18 14:50 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-07-18 15:35 UTC, merged