Gl qcom image processing
KhronosGroup/glslang pull request #3303
Opened 2023-08-16 07:48 UTC by wooyoungqcom

[extension]  GL_QCOM_image_processing support

2023-08-17 18:17 UTC, arcady-lunarg requested changes
Looks fine overall, just a couple of minor nits that need to be addressed before this is merged.

2023-08-17 18:17 UTC, arcady-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +	      }
Stray whitespace diff

2023-08-17 18:17 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +  spv::Id opc = builder.getOpCode(id);
This type should be spv::Op

2023-08-21 19:11 UTC, wooyoungqcom commented on SPIRV/GlslangToSpv.cpp
> +  spv::Id opc = builder.getOpCode(id);
Thanks, much. I updated the branch with the fixes.

2023-08-21 23:22 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-08-22 00:14 UTC, merged