Add GL_EXT_texture_shadow_lod support
KhronosGroup/glslang pull request #3304
Opened 2023-08-17 18:55 UTC by ncesario-lunarg

Closes #3302.

2023-08-17 18:58 UTC, ncesario-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +                symbolTable.setSingleFunctionExtensions("texture(sAS21;vf4;f1;", 1, &E_GL_EXT_texture_shadow_lod);
I'm not a fan of this, but not sure how else to go about it.

I looked into building the mangled names at runtime (I know the mangled names are unlikely to change, but it's still a possibility), but it looks like we don't have the infrastructure for doing that in a "one-off" style, and I'm not sure it's worth adding just for this extension.

I'm happy to modify this if anyone has suggestions.

2023-08-23 22:52 UTC, greg-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +                symbolTable.setSingleFunctionExtensions("texture(sAS21;vf4;f1;", 1, &E_GL_EXT_texture_shadow_lod);
Yeah, I think splitting out and calling the code that mangles the names is the only way to make this cleaner. Is it worth it? If it doesn't add too much complexity or overhead, it might be nice. If you want to get this to Dan as soon as possible, maybe create an issue to fix it up later.

2023-08-24 06:01 UTC, ncesario-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +            TempParser parser(textureShadowLodFunctions, language, version, profile, spvVersion);
This still feels a bit hacky, but should be more "correct" in the sense that the name mangling is no longer hard-coded.

2023-09-04 22:44 UTC, arcady-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +            TempParser parser(textureShadowLodFunctions, language, version, profile, spvVersion);
This feels like a big hammer to use here, with things like the memory consumption. On the other hand, I think it's not actually that much extra memory, the heaviest struct is TParseContext at some 30k, and if it becomes a big issue we can do the work of pulling the function mangler out somewhat more cleanly.

2023-09-05 19:41 UTC, arcady-lunarg requested changes
Looks like there is some dead code that needs to be removed and I would like to see the test generate some SPIR-V, but otherwise the change looks fine.

2023-09-05 19:41 UTC, arcady-lunarg commented on glslang/MachineIndependent/SymbolTable.h
> +
Looks like dead code?

2023-09-05 19:41 UTC, arcady-lunarg commented on glslang/MachineIndependent/SymbolTable.h
> +    {
Looks like dead code?

2023-09-05 21:11 UTC, ncesario-lunarg commented on glslang/MachineIndependent/Initialize.cpp
> +            TempParser parser(textureShadowLodFunctions, language, version, profile, spvVersion);
> This feels like a big hammer to use here...

I agree, I'm not a fan, but I couldn't find a better way, at least with the existing code. If this shows up again, pulling it out makes sense to me, though I'm not sure how to do that without reimplementing the parser to some degree.

2023-09-05 21:11 UTC, ncesario-lunarg commented on glslang/MachineIndependent/SymbolTable.h
> +
Yep, I forgot to get rid of this. Thanks for the catch!

2023-09-05 22:59 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-09-05 23:00 UTC, merged