RFC: Add --no-link option and [[export]] attribute
KhronosGroup/glslang pull request #3319
Opened 2023-08-24 02:59 UTC by ncesario-lunarg

This change experiments with adding a "compile-only" option to glslang as well as an `[[export]]` function attribute allowing functions to be exported and then later used by spirv-link.

Proposed usage:
```bash
glslang -V --no-link myfuncs.comp -o myfuncs.spv
```

Where myfuncs.comp looks something like
```glsl
#version 450

[[export]]
int foo(...) { ... }

[[export]]
float bar(...) { ... }
```

And where "foo" and "bar" will get the "Export" linkage decoration in the resulting spir-v.

To be more "complete" this change should also:
- Add an `[[import]]` attribute for importing functions from another spir-v module
- Allow variables to be exported and imported in addition to functions (ideally using the same `[[export]]`/`[[import]]` attributes)
- Specify additional spir-v binaries at link time

However, in its current (functional) form, this change could benefit the ongoing improvements to the GPU-AV workflow in Vulkan-ValidationLayers. Before spending anymore time on this, I'm hoping to get some feedback on the overall approach here. I know `[[export]]`/`[[import]]` are not official attributes and that may not be the best mechanism for achieving the end goal here (e.g., just exporting all functions when in compile-only mode would work for the purposes of GPU-AV).

2023-09-06 15:17 UTC, ncesario-lunarg commented
FYI @jeremyg-lunarg.

2023-09-06 15:38 UTC, jeremyg-lunarg commented
I'll update my code this morning and make sure it works. I don't anticipate this change being a problem. Thanks!

2023-09-06 16:44 UTC, jeremyg-lunarg commented
Works for me locally! I pushed my updated VVL branch to depend on the newest commit.

2023-09-11 23:51 UTC, arcady-lunarg requested changes
Just a few minor questions and comments, but on the whole this looks good to me.

2023-09-11 23:51 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +spv::LinkageType TGlslangToSpvTraverser::convertGlslangToSpv(glslang::TLinkType linkType) {
Could you give this function a better name? Given we have GlslangToSpv, convertGlslangToSpv sounds very confusing. Maybe something like glslangToSpvLinkageType?

2023-09-11 23:51 UTC, arcady-lunarg commented on SPIRV/SpvBuilder.cpp
> +    if (auto linkType = function->getLinkType(); linkType != LinkageTypeMax) {
I don't know that we have a rule against multiple statements in an if condition, but this is the only place in the codebase such a construct appears. I would prefer you hoist the linkType declaration out.

2023-09-11 23:51 UTC, arcady-lunarg commented on Test/baseResults/spv.exportFunctions.comp.out
> +                              Decorate 7(add(f1;f1;) Linkage Attributes 6579297 0
That random constant in there is apparently the name of the exported symbol, unfortunate that it gets printed in such an unreadable way but I don't think it's worth fixing in this change.

2023-09-13 15:54 UTC, ncesario-lunarg commented on SPIRV/GlslangToSpv.cpp
> +spv::LinkageType TGlslangToSpvTraverser::convertGlslangToSpv(glslang::TLinkType linkType) {
Yes, my original intent was to merge this with one of the existing `convertGlslangToSpvType`, but hadn't found a good way to do that and forgot to circle back. I'll rename it for now.

2023-09-13 15:54 UTC, ncesario-lunarg commented on SPIRV/GlslangToSpv.cpp
> +spv::LinkageType TGlslangToSpvTraverser::convertGlslangToSpv(glslang::TLinkType linkType) {
Is `convertGlslangLinkageToSpv` sound ok?

2023-09-13 16:07 UTC, ncesario-lunarg commented on Test/baseResults/spv.exportFunctions.comp.out
> +                              Decorate 7(add(f1;f1;) Linkage Attributes 6579297 0
Yeah, this is really unreadable. The `spirv-dis` output makes a lot more sense:
```asm
...
OpName %7 "add(f1;f1;"
...
OpDecorate %7 LinkageAttributes "add" Export
...
%7 = OpFunction %2 None %4
...
```
I'm not sure how easy this output is to fix for the tests (or the ROI for such a change).

2023-09-18 19:07 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +spv::LinkageType TGlslangToSpvTraverser::convertGlslangToSpv(glslang::TLinkType linkType) {
Yeah, that seems like a cromulent name.

2023-09-18 19:09 UTC, arcady-lunarg commented on glslang/HLSL/hlslAttributes.cpp
> +        else if (name == "export")
What I meant is that you should put it under the `if (nameSpace == "spv")` block so that in the HLSL, the attribute is spelled `[spv::export]`.

2023-09-18 19:19 UTC, ncesario-lunarg commented on glslang/HLSL/hlslAttributes.cpp
> +        else if (name == "export")
ah, yes, I should have put it there.

2023-09-18 21:30 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-09-18 21:31 UTC, merged