Add support for GL_NV_displacement_micromap.
KhronosGroup/glslang pull request #3324
Opened 2023-08-30 22:58 UTC by alelenv

SPV Headers : https://github.com/KhronosGroup/SPIRV-Headers/pull/374
GLSL : https://github.com/KhronosGroup/GLSL/pull/213
SPV : https://github.com/KhronosGroup/SPIRV-Registry/pull/217

2023-08-31 16:34 UTC, arcady-lunarg commented
Does this depend on a change to spirv-tools (for the SPIR-V validator)? If so, that will need to be merged first and known_good.json updated so that the tests can pass. I can review the code changes here in the meantime however.

2023-09-05 17:45 UTC, alelenv commented
@arcady-lunarg : Nothing required in validator since just adds a few builtins and decorations. Can updated if anything else is expected
Yes will required headers to be merged before we can flip known_good

Thanks for reviewing

2023-09-21 04:09 UTC, alelenv commented
@arcady-lunarg : I have updated known_good and all tests are passing
Please re-review

Thanks

2023-09-27 17:31 UTC, alelenv commented
@arcady-lunarg : Gentle one week ping!
Thanks

2023-09-28 17:08 UTC, ncesario-lunarg reviewed
This LGTM aside from the spirv-tools update, which will need to happen separately. @jeremy-lunarg I think we are planning on updating this soon?

2023-09-28 19:46 UTC, arcady-lunarg requested changes
Just one minor nit (the unused variable), otherwise this looks good.

2023-09-28 19:46 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +        glslang::TOperator rqOp = node->getOp();
This variable appears to be unused, could you remove it?

2023-09-29 01:18 UTC, alelenv commented on SPIRV/GlslangToSpv.cpp
> +        glslang::TOperator rqOp = node->getOp();
Done, thanks for the catch!

2023-10-02 18:06 UTC, alelenv commented
@arcady-lunarg : Please approve and merge

2023-10-02 18:20 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2023-10-02 19:07 UTC, merged