Fix interpolant ES error
KhronosGroup/glslang pull request #3335
Opened 2023-09-15 17:11 UTC by ncesario-lunarg

The restriction of no swizzling and no struct fields as an interpolant were not being checked when using the ES profile.

Fixes #3277.

2023-09-15 17:13 UTC, ncesario-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                [&isValid, &isIn, &interpolantErrorMsg, esProfile, &structAccessOp](const TIntermNode& n) {
@arcady-lunarg @jeremy-lunarg I went back and forth with creating a dedicated function to fix this or a more generic function to traverse. Let me know what you prefer style-wise.

2023-09-15 17:14 UTC, ncesario-lunarg commented on glslang/MachineIndependent/localintermediate.h
> +#include <vector>
The only actual addition here is `<functional>`. `clang-format` put them in alphabetical order.

2023-09-15 23:33 UTC, arcady-lunarg requested changes
A couple comments on some details but the overall approach is good. Thanks for adding some pretty comprehensive tests.

2023-09-15 23:33 UTC, arcady-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                [&isValid, &isIn, &interpolantErrorMsg, esProfile, &structAccessOp](const TIntermNode& n) {
I think it's better to keep it inline but I also would prefer a brief comment explaining what this is doing.

2023-09-15 23:33 UTC, arcady-lunarg commented on glslang/MachineIndependent/localintermediate.h
> +    static const TIntermTyped* traverseLValueBase(const TIntermTyped*, bool swizzleOkay, bool bufferReferenceOk = false,
I'm a bit confused as to why a) this returns a value since your one use of it doesn't consume the return value at all and b) why proc has a default value. Were you trying to combine `findLValueBase` and `traverseLValueBase` and just didn't finish the job? It might not be a bad idea to combine those two btw since the traversal code is annoying and would be best written only once.

2023-09-18 14:58 UTC, ncesario-lunarg commented on glslang/MachineIndependent/localintermediate.h
> +    static const TIntermTyped* traverseLValueBase(const TIntermTyped*, bool swizzleOkay, bool bufferReferenceOk = false,
Yes, that was my original intent, but felt it was a little messy and so I wanted to get some feedback first. I would also prefer these to be combined, but wasn't sure what the preference would be for the generic traversal code. If you're ok with the generic approach, I'll combine them.

2023-11-09 00:03 UTC, arcady-lunarg commented on glslang/MachineIndependent/localintermediate.h
> +    static const TIntermTyped* traverseLValueBase(const TIntermTyped*, bool swizzleOkay, bool bufferReferenceOk = false,
I think it's cleaner this way, the complicated traversal logic exists only once.

2023-11-09 00:07 UTC, arcady-lunarg requested changes
Thanks, I think it's cleaner like this, one small nit left to address and this can be merged.

2023-11-09 00:07 UTC, arcady-lunarg commented on glslang/MachineIndependent/localintermediate.h
>      static const TIntermTyped* findLValueBase(const TIntermTyped*, bool swizzleOkay , bool BufferReferenceOk = false);
I think you need to delete this because the function doesn't exist.

2023-11-10 20:47 UTC, ncesario-lunarg commented on glslang/MachineIndependent/localintermediate.h
>      static const TIntermTyped* findLValueBase(const TIntermTyped*, bool swizzleOkay , bool BufferReferenceOk = false);
Ah, yep, thanks for catching that!

2023-11-11 15:53 UTC, arcady-lunarg approved these changes

2023-11-11 15:53 UTC, merged