Implement relaxed rule for opaque struct members
KhronosGroup/glslang pull request #3365
Opened 2023-10-16 14:01 UTC by sbourasse

This PR is a companion to another PR we recently opened on `KhronosGroup/GLSL` : https://github.com/KhronosGroup/GLSL/pull/218
It implements the procedure described in the suggested changes to `GL_EXT_vulkan_glsl_relaxed`.

Samplers are extracted out of structures and moved to the topmost level available. In the context of uniform, that's the global uniform block. For structures passed as function parameters, we create invisible parameters and properly route arguments to them.

We also extend the `vk.relaxed.frag` test shader to demonstrate these added capabilities.

2023-10-16 14:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3365) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3365) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3365) it.</sub>

2023-10-17 18:06 UTC, arcady-lunarg commented
Looks like ASAN found some issues with your patch, do you want to address them before I take a look to review the changes? Also, is there some sequencing needed between this and the PR to then GLSL repo?

2023-10-18 18:44 UTC, ncesario-lunarg commented
> I haven't entirely figured out how memory ownership is handled within the codebase

Some classes use the `TPoolAllocator` rather than the standard C++ allocator. Allocations made from the pool allocator are "free" (this is covered at the [end of the README](https://github.com/KhronosGroup/glslang#basic-internal-operation)). I plan on making these allocations more obvious, so that it's easier to know which allocations must be cleaned up and which ones don't need to.

2023-10-18 19:03 UTC, ncesario-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                      TParameter* memberParam = new TParameter();
`TParameter` does not use the pool allocator (by default at least), so this is using the standard allocator and would need to be cleaned up. I'm not sure if this is the right way to go about this. You could use the pool allocator, but it seems like you could also retrieve the necessary parameters from `function` after `vkRelaxedRemapFunctionParameter` is called (though you may need to add an additional field to `TParameter` to pick out the parameters you want)?

2023-10-18 19:12 UTC, ncesario-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                      TString* memberName = new TString(path);
See previous comment about `TString` allocation.

2023-10-24 13:50 UTC, sbourasse commented on glslang/MachineIndependent/ParseHelper.cpp
> +
This is unintended, most likely leftovers from earlier developments.

2023-10-24 13:52 UTC, sbourasse commented on glslang/MachineIndependent/ParseHelper.cpp
> +                      TParameter* memberParam = new TParameter();
I replaced the last function parameter with a vector of integer to avoid changing `TParameter`, but maybe it would be better to properly flag parameters that are implicitly created during this pass ?

2023-10-24 13:52 UTC, sbourasse commented on glslang/MachineIndependent/ParseHelper.cpp
> +                      TString& structMemberName = *(new TString(path));
True, this should be a straight copy

2023-10-24 14:05 UTC, sbourasse commented
Thanks for reviewing ! My latest changes should fix leaks

2023-11-16 20:52 UTC, arcady-lunarg requested changes
I have a couple of minor nits but overall this seems fine. It's a lot of fairly complicated code but that code is only used in relaxed mode.

2023-11-23 10:10 UTC, sbourasse commented on glslang/MachineIndependent/ParseHelper.cpp
> +bool TParseContext::vkRelaxedRemapUniformVariable(const TSourceLoc& loc, TString& identifier, const TPublicType& publicType,
It's forwarded to `vkRelaxedRemapUniformMembers`. I looked across the file for another `publicType` that seemed unused but didn't find any.

2023-11-28 15:53 UTC, arcady-lunarg approved these changes
Thanks, looks good now.

2023-11-29 00:19 UTC, merged