Add a helper applySpirvDecorate to handle spirv_decorate_xxx directives
KhronosGroup/glslang pull request #3390
Opened 2023-11-07 07:14 UTC by amdrexu

Some code paths could be shared.

2023-11-07 16:50 UTC, arcady-lunarg requested changes

2023-11-07 16:50 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +// Apply SPIR-V decorations to the SPIR-V object (provided by SPIR-V ID). If member index is valid (>= 0), the
I am not a fan of using this magical -1 value here. Maybe it would be cleaner to use something like `std::optional`?

2023-11-07 17:08 UTC, ncesario-lunarg commented on SPIRV/GlslangToSpv.cpp
> +// Apply SPIR-V decorations to the SPIR-V object (provided by SPIR-V ID). If member index is valid (>= 0), the
➕

2023-11-08 05:07 UTC, amdrexu commented on SPIRV/GlslangToSpv.cpp
> +// Apply SPIR-V decorations to the SPIR-V object (provided by SPIR-V ID). If member index is valid (>= 0), the
Thank you. It is a good idea. I revise the change.

2023-11-08 18:35 UTC, ncesario-lunarg approved these changes

2023-11-09 03:04 UTC, arcady-lunarg approved these changes

2023-11-09 15:49 UTC, merged