Fix some GCC warnings
KhronosGroup/glslang pull request #3396
Opened 2023-11-07 23:42 UTC by ncesario-lunarg

This fixes some -Wconversion warnings from gcc.

There are still several GCC conversion warnings in Types.h due to the use of bit fields that will be resolved in a future change.

2023-11-09 00:19 UTC, arcady-lunarg requested changes
I think the warning actually found us a genuine bug, we should probably fix that.

2023-11-09 00:19 UTC, arcady-lunarg commented on glslang/Include/ConstantUnion.h
> +        case EbtInt16:  returnValue.setI8Const(static_cast<int8_t>(i8Const % constant.i16Const)); break;
I think this is an actual bug and this should be setI16Const. Adding the warning turned out to be helpful after all!

2023-11-10 21:17 UTC, ncesario-lunarg commented on glslang/CMakeLists.txt
> +set_source_files_properties(MachineIndependent/glslang_tab.cpp PROPERTIES COMPILE_FLAGS -Wno-unused-but-set-variable)
@arcady-lunarg this will get rid of the `warning: variable 'yynerrs' set but not used [-Wunused-but-set-variable]
` warning. I think  it's ok to turn this off for a generated file like this.

2023-11-28 15:51 UTC, arcady-lunarg requested changes
Still one issue left and this can be merged I think.

2023-11-29 00:15 UTC, arcady-lunarg approved these changes
LGTM, thanks

2023-11-29 00:16 UTC, merged