support GL_ARB_texture_multisample extension.
KhronosGroup/glslang pull request #3430
Opened 2023-11-29 01:36 UTC by jimihem

This extension allows the use of "texelFetch" and "textureSize" with 2DMS sampler.
#version 140
out float result;

uniform sampler2DMS data;
uniform sampler2DMSArray data1;
void main()
{
result = texelFetch(data, ivec2(0), 3).r;
ivec2 temp = textureSize(data);
result = texelFetch(data1, ivec3(0), 3).r;
ivec3 temp1 = textureSize(data1);
}

2023-11-29 16:26 UTC, ncesario-lunarg requested changes
I think this looks good apart from the test file.

2023-11-29 16:26 UTC, ncesario-lunarg commented on Test/GL_ARB_texture_multisample.vert
I'm guessing this is not supposed to be empty?

2023-11-29 16:26 UTC, ncesario-lunarg commented on Test/baseResults/GL_ARB_texture_multisample.vert.out
Probably not the desired output?

2023-11-29 16:26 UTC, ncesario-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                if ((typeName == "sampler2DMS" || typeName == "sampler2DMSArray") && version == 140)
I think this makes sense after looking at the spec, but just to clarify, this extension is _only_ required for version 140? i.e., it is not possible to use this extension prior to 140?

2023-11-30 03:16 UTC, jimihem commented on glslang/MachineIndependent/ParseHelper.cpp
> +                if ((typeName == "sampler2DMS" || typeName == "sampler2DMSArray") && version == 140)
Thanks for your suggesstion, I have made modifications to this PR.

2023-12-11 06:07 UTC, jimihem commented on Test/GL_ARB_texture_multisample.vert
> +ivec3 temp1 = textureSize(data1);
I have organized the format @ncesario-lunarg

2023-12-11 21:36 UTC, ncesario-lunarg reviewed
One question, but LGTM.

Looks like there are really 2 distinct changes here; I'm not sure how they are related?

2023-12-11 21:36 UTC, ncesario-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                if ((typeName == "sampler2DMS" || typeName == "sampler2DMSArray") && version <= 140)
Do the integer versions of these functions need to be handled?

2023-12-13 22:24 UTC, arcady-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                if ((typeName == "sampler2DMS" || typeName == "sampler2DMSArray") && version <= 140)
I think rather than calling `getString()` here it would be better to directly check the relevant property, which I guess is `getSampler()->isMultiSample()`. And that would handle the usampler/isampler case transparently as well.

2023-12-13 22:25 UTC, arcady-lunarg requested changes
Could you add tests for usampler2DMS and isampler2DMS just for completeness? Also, I think it would be better not to construct the sampler type string and just check the TSampler's properties directly via the appropriate accessors.

2023-12-28 23:38 UTC, arcady-lunarg approved these changes
Thanks, LGTM

2023-12-28 23:38 UTC, merged