Add support for GL_ARB_shading_language_include
KhronosGroup/glslang pull request #3453
Opened 2023-12-15 21:09 UTC by ncesario-lunarg

Add support for GL_ARB_shading_language_include. Usage is identical to the way GL_GOOGLE_include_directive currently works glslang (since GL_ARB_shading_language_include is inherently a runtime feature and glslang is an offline compiler).

Users can simulate their runtime environment by using a custom glslang::TShader::Includer or using filenames that match their GL runtime names.

Closes #249.

2023-12-28 22:13 UTC, arcady-lunarg requested changes
My reading of the [spec](https://registry.khronos.org/OpenGL/extensions/ARB/ARB_shading_language_include.txt) seems to indicate that the extension can be used with any version of GLSL, the code should be changed to reflect that, and it also obviates the need for one of the tests.

2023-12-28 22:13 UTC, arcady-lunarg commented on glslang/MachineIndependent/preprocessor/Pp.cpp
> +                    if (parseContext.version >= 150) return { E_GL_GOOGLE_include_directive, E_GL_ARB_shading_language_include };
This isn't actually correct, if you read the extension spec, it's _written against_ 1.50 but _requires_ 1.10, so the extension can be used for any version.

2024-01-17 19:27 UTC, ncesario-lunarg commented on glslang/MachineIndependent/preprocessor/Pp.cpp
> +                    if (parseContext.version >= 150) return { E_GL_GOOGLE_include_directive, E_GL_ARB_shading_language_include };
Yep, this should be fixed now.

2024-01-31 21:11 UTC, arcady-lunarg commented on Test/baseResults/preprocess.arb_shading_language_include.vert.err
> +ERROR: 0:7: '#include' : Could not process include directive for header name: bar.h
Is this failure expected? The test looks like it's supposed to pass.

2024-02-15 22:28 UTC, ncesario-lunarg commented on Test/baseResults/preprocess.arb_shading_language_include.vert.err
> +ERROR: 0:7: '#include' : Could not process include directive for header name: bar.h
I believe this is correct. This is effectively checking that the output is _not_

```
ERROR: 0:7: '#include' : required extension not requested: GL_GOOGLE_include_directive
```

That said, all the pre-processor test output/logic is a bit confusing to me.

All the preprocessor tests use the default "ForbidIncluder": https://github.com/KhronosGroup/glslang/blob/d84255296c3d19642515237c8d016bb685bd0bed/gtests/TestFixture.h#L658 which means that no include files can be resolved.

e.g., https://github.com/KhronosGroup/glslang/blob/main/Test/preprocessor.include.enabled.vert is a "positive" test for `GL_GOOGLE_include_directive`, yet it produces errors because none of the include paths can be resolved: https://github.com/KhronosGroup/glslang/blob/main/Test/baseResults/preprocessor.include.enabled.vert.err.

2024-02-16 00:08 UTC, arcady-lunarg commented on Test/baseResults/preprocess.arb_shading_language_include.vert.err
> +ERROR: 0:7: '#include' : Could not process include directive for header name: bar.h
Ah, that explains it. We can leave it as is for now, and maybe I will do a followup change to fix the preprocessor testing.

2024-02-27 23:26 UTC, arcady-lunarg approved these changes

2024-02-27 23:26 UTC, merged