Update CHANGES for release 14.0.0
KhronosGroup/glslang pull request #3461
Opened 2023-12-21 23:04 UTC by jeremy-lunarg

2023-12-21 23:54 UTC, arcady-lunarg commented on CHANGES.md
> +* Remove various warning suppression pragmas
This doesn't need to be in the changelog, it's not a user-facing change.

2023-12-21 23:55 UTC, arcady-lunarg requested changes
One line that can be removed, but otherwise I think this is fine.

2023-12-22 00:07 UTC, ncesario-lunarg reviewed
LGTM after Arcady's comment is addressed.

2023-12-22 16:04 UTC, jeremy-lunarg commented on CHANGES.md
> +* Remove various warning suppression pragmas
Removed. Thanks!

2023-12-22 16:13 UTC, ncesario-lunarg approved these changes

2023-12-22 16:20 UTC, arcady-lunarg approved these changes

2023-12-22 17:11 UTC, merged