Clean up line tracking logic for debug info
KhronosGroup/glslang pull request #3496
Opened 2024-02-02 01:42 UTC by qingyuanzNV

This patch cleans up the line tracking logic when debug info is turned on, including:
1. Add correct file tracking. We used to have `sourceFileStringId` and `currentFileId` in the `SpvBuilder`, but both were always OpString id of the main file. Renamed them to `mainFileId` and `currentFileId` and implemented file tracking accordingly.
2. Make insertion of OpLine/OpDebugLine/OpDebugScope lazy. We used to insert OpLine right after setting the current debug source location, sometimes resulting in multiple cascading OpLines without any meaningful instructions in between. By making the process lazy, an OpLine is only inserted when an instruction is added with a dirty line tracker.
3. Added per-block line/scope tracker. So whenever an OpLine/OpDebugLine/OpScope is inserted, the state is stored in the `Block` instead of `SpvBuilder`. This is how the standard defines the lifetime of such instruction.

Also, some minor changes are:
1. Skip setting debug source location for linking object at the end of the AST
2. Rename some functions to better reflect that they are debug info related
3. No longer generate an OpLine preceding an OpFunction when Non-Semantic Debug is requested. The line information is available via the extension already.

As a result of this patch, we should have non-semantic debug reporting the correct file for variables, functions and .etc.

2024-02-08 18:03 UTC, qingyuanzNV commented
@arcady-lunarg We are trying to catch an internal deadline and put this patch in. Could you help review this PR? Thanks!

2024-02-08 18:51 UTC, arcady-lunarg commented
Yes, I am going to review it today, it also fixes some issues for us. I was
at Vulkanised the past few days and didn't get a chance to look at it in
enough detail.

On Thu, Feb 8, 2024, 10:04 Qingyuan Zheng ***@***.***> wrote:

> @arcady-lunarg <https://github.com/arcady-lunarg> We are trying to catch
> an internal deadline and put this patch in. Could you help review this PR?
> Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KhronosGroup/glslang/pull/3496#issuecomment-1934671448>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5I72BZB5KDWZPUP6Q5OET3YSUHRBAVCNFSM6AAAAABCV4UKA6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMZUGY3TCNBUHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-08 23:27 UTC, arcady-lunarg requested changes
Just a couple of nits, but overall I think this looks good, and the results seem fine. Also your PR description is great, and you should use some version of it as a commit message (and if not, I'll probably do "squash and merge" and do it anyway).

2024-02-08 23:27 UTC, arcady-lunarg commented on SPIRV/SpvBuilder.h
> +        // dirtyLineTracker = true;
Do you have a pending change to clean this up? I don't really like the idea of checking in TODOs or commented code. Actually, you should just delete the commented out line, but keep the TODO comment for now.

2024-02-09 17:11 UTC, qingyuanzNV commented on SPIRV/spvIR.h
> +    std::optional<spv::Id> currentDebugScope;
Added assert.

Technically, there's an OpDebugNoScope to clear the current scope. But as we never generate the op and I don't see a use case of the op in glslang, I didn't add a way to clear the tracker to keep it simple.

2024-02-09 17:13 UTC, qingyuanzNV commented on SPIRV/SpvBuilder.h
> +        // dirtyLineTracker = true;
Done

2024-02-09 17:25 UTC, qingyuanzNV commented
Could you help squash and merge with the commit message below (so it's easier for you to review the new changes):
```
Clean up the debug line info tracking and generation. 
- Correctly populate the field `currentFileId` with the presence of include directive
- Support lazy OpLine/OpDebugLine generation only when a real instruction is added instead of a debug location is set
- Improve the debug location tracking to per-block instead of just per-builder
- A few bug fixes related to debug source info
```

2024-02-09 17:38 UTC, qingyuanzNV commented
By the way, one important change of this PR is that I added an `addInstruction(...)` to `SpvBuilder` to hijack all instructions added to the current build point. You guys might need be alert on this when reviewing new changes to make sure that all new instructions added to the current build point should go through that function instead of directly calling `buildPoint.addInstruction(...)`.

2024-02-09 18:26 UTC, arcady-lunarg approved these changes
LGTM, thanks, this is a huge improvement.

2024-02-09 18:27 UTC, merged