NV_shader_atomic_fp16_vector
KhronosGroup/glslang pull request #3519
Opened 2024-02-14 21:41 UTC by jeffbolznv

This implements the old OpenGL/GLSL extension https://registry.khronos.org/OpenGL/extensions/NV/NV_shader_atomic_fp16_vector.txt using the new SPIR-V extension https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/NV/SPV_NV_shader_atomic_fp16_vector.html

2024-02-14 22:41 UTC, arcady-lunarg requested changes
One minor nit, otherwise this looks fine. What a curious hardware capability to have.

2024-02-14 22:41 UTC, arcady-lunarg commented on glslang/MachineIndependent/ParseHelper.cpp
> +                 (fnCandidate.getName().compare(0, 19, "imageAtomicMin") == 0) ||
Should this be 14 rather than 19 here? Unfortunately, `std::basic_string::starts_with` was only added in c++20, but maybe a helper would be good to avoid needing to count characters.

2024-02-14 22:41 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +                                 const glslang::TType &opType);
It seems kind of odd to be passing both the TType and TBasicType here but I kind of see why it's necessary, so I think it's fine to leave this as is.

2024-02-14 23:03 UTC, jeffbolznv commented on glslang/MachineIndependent/ParseHelper.cpp
> +                 (fnCandidate.getName().compare(0, 19, "imageAtomicMin") == 0) ||
Done, thanks.

2024-02-14 23:17 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2024-02-14 23:55 UTC, merged

2024-02-15 18:30 UTC, AnyOldName3 commented
First things first, I don't know if this is how things are supposed to work, so I apologise for the noise if I'm unnecessarily raising red flags.

After this PR was merged, the new test fails unless SPIRV-Tools and SPIRV-Headers are updated to the new commit in `known_good.json`. That's fine on its own (although it briefly made me think I'd broken something on my end), but I imagine that if `ALLOW_EXTERNAL_SPIRV_TOOLS` is set and the system-installed library is used, it will probably be an older commit and the test will fail there, too. I just wanted to make sure no one had forgotten to add some conditional compilation if a feature check failed.

If instead it's expected that some tests fail with commits other than the one in `known_good.json`, it might be a good idea to document that, e.g. in the testing part of the readme and the docstring for the `ALLOW_EXTERNAL_SPIRV_TOOLS` CMake option.

2024-02-15 20:28 UTC, arcady-lunarg commented
The only supported configuration is with the versions of headers/tools in `known_good.json`. If you're using your own version of SPIRV-Tools, you're on your own. That's why we didn't even have the `ALLOW_EXTERNAL_SPIRV_TOOLS`. @AnyOldName3 if you think the documentation around this option could be improved, patches are certainly welcome.