Support for SPV_QCOM_image_processing2
KhronosGroup/glslang pull request #3539
Opened 2024-03-05 08:47 UTC by wooyoungqcom

2024-03-19 22:24 UTC, arcady-lunarg requested changes
The code itself looks fine, but your tests aren't being run, you need to add them to the appropriate list of tests in `gtests/Spv.FromFile.cpp` and generate base results that will end up in the `Test/baseResults` directory by running `build/gtests/glslangtests --update-mode` or similar after you have added the tests to the test list and rebuilt.
Also please revert the whitespace change to `known_good.json`.

2024-03-19 22:24 UTC, arcady-lunarg commented on known_good.json
This looks like a whitespace-only change, could you revert it?

2024-03-19 22:57 UTC, wooyoungqcom commented
Thank you so much for the review.
I hope I made all the changes you mentioned.

2024-03-20 22:55 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2024-03-20 22:56 UTC, merged