Update CHANGES for 14.4.0
KhronosGroup/glslang pull request #3740
Opened 2024-09-23 23:47 UTC by jeremy-lunarg

2024-09-24 15:40 UTC, arcady-lunarg requested changes
Thanks for putting this together, I have a few suggestions.

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Explicitly export symbols from libSPVRemapper
I would condense all the symbol visibility changes to one point at put it at the top.
Something like:
Explicitly export all symbols that are part of the public API. Building glslang as a DLL or shared library is now possible and supported.
Maybe we should even put something in the README?

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Silence preprocessor '#' error reporting for inactive #if/#ifdef/#elif/#else
"error reporting in inactive #if/#else/... blocks" perhaps?

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Add setSourceFile and addSourceText to TShader
Add *public* setSourceFile and addSourceText methods to TShader *class*

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Fix initialization of arrays in TGlslIoMapper
Internal fix, I think there's no need to call this out.

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Add missing calls SetThreadPoolAllocator
Internal fix, not sure if this needs to be called it. If you call it out, probably best to say where.

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Fix undefined behaviors caused by integer overflows
Internal fix

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Fix undefined behavior exposed by unscoped enumerated types
Internal fix

2024-09-24 15:40 UTC, arcady-lunarg commented on CHANGES.md
> +* Report error if generating SPIR-V for misconfigured glslang
I would actually call out the main thing here:
* Allow building glslang without the SPIR-V backend using the new ENABLE_SPIRV build option.

The error thing isn't a change from the previous released version (which didn't allow building without SPIR-V at all).

2024-09-24 18:48 UTC, jeremy-lunarg commented on CHANGES.md
> +* Explicitly export symbols from libSPVRemapper
`Explicitly export all symbols that are part of the public API`

I'll put that in the breaking changes section instead of what I have.

`Building glslang as a DLL or shared library is now possible and supported.`

That part sounds like it should go in the README. I'll add that to my PR as well.

2024-09-24 18:54 UTC, jeremy-lunarg commented on CHANGES.md
> +* Add missing calls SetThreadPoolAllocator
I'll remove it.

2024-09-24 18:56 UTC, jeremy-lunarg commented on CHANGES.md
> +* Fix undefined behaviors caused by integer overflows
I'll remove but only added to highlight improved stability.

2024-09-24 19:05 UTC, jeremy-lunarg commented
Thanks @arcady-lunarg. Please take another look.

2024-09-24 19:08 UTC, jeremy-lunarg commented
@arcady-lunarg, do you think we should remove any of the old bullets from `News` section of the README?

2024-09-25 20:54 UTC, arcady-lunarg requested changes
A couple more nits, otherwise I think this is fine.

2024-09-25 20:54 UTC, arcady-lunarg commented on CHANGES.md
> +* Silence preprocessor '#' error reporting in inactive #if/#ifdef/#elif/#else
Could you add the word "blocks" at the end?

2024-09-25 20:54 UTC, arcady-lunarg commented on CHANGES.md
> +* Add public setSourceFile and addSourceText to TShader
"methods to TShader" (or even "methods to TShader class")

2024-09-25 22:59 UTC, arcady-lunarg approved these changes
LGTM, thanks.

2024-09-25 23:10 UTC, merged