Emit `OpModfStruct` for GLSL `EOpModf` instead of `OpModf` (fixes #3756)
KhronosGroup/glslang pull request #3757
Opened 2024-10-07 21:56 UTC by chyyran

My attempt at fixing https://github.com/KhronosGroup/glslang/issues/3756.

Seems like it validates, some tests are breaking due to expecting `OpModf` but I'm not sure how to update the expected outputs for those.

2024-10-07 21:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3757) it.</sub>

2024-10-07 22:01 UTC, chyyran commented
Failing unit tests

```
2: [  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_400_frag, where GetParam() = "spv.400.frag"
2: [  FAILED  ] Glsl/CompileVulkanToSpirvTest.FromFile/spv_Operations_frag, where GetParam() = "spv.Operations.frag"
2: [  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_float32_frag, where GetParam() = "spv.float32.frag"
2: [  FAILED  ] Glsl/CompileVulkan1_1ToSpirvTest.FromFile/spv_float64_frag, where GetParam() = "spv.float64.frag"
2: [  FAILED  ] Glsl/CompileVulkanToSpirvTestAMD.FromFile/spv_float16_frag, where GetParam() = "spv.float16.frag"
```

2024-10-08 20:02 UTC, chyyran commented
Seems like more tests need to be updated. I ran glslangtests with --update-mode but it seems more needs to be done?

2024-10-08 22:41 UTC, chyyran commented
Managed to get the `runtests` tests to run and updated those results as well.

2024-10-14 20:50 UTC, chyyran commented
@arcady-lunarg any updates on getting this merged?

2024-10-21 23:24 UTC, arcady-lunarg requested changes
The code actually looks fine, I don't really like the way the comments are worded though, could you please reword them?

2024-10-21 23:24 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +                // Using 16-bit whole number operand, enable extension E_SPV_AMD_gpu_shader_half_float
I think this can be removed, the code is kind of self-explanatory

2024-10-21 23:24 UTC, arcady-lunarg commented on SPIRV/GlslangToSpv.cpp
> +            // The two members of the returned struct and x must all be the same type.
This comment should maybe be more like "The returned struct has two members of the same type as the first argument"

2024-10-21 23:35 UTC, chyyran commented
@arcady-lunarg address nits as of 5c784d6

2024-10-25 15:57 UTC, arcady-lunarg approved these changes

2024-10-25 15:58 UTC, merged