python 3.12: remove deprecated datetime.utcfromtimestamp
KhronosGroup/glslang pull request #3771
Opened 2024-10-24 00:03 UTC by selfisekai

2024-10-24 00:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3771) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KhronosGroup/glslang?pullRequest=3771) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KhronosGroup/glslang?pullRequest=3771) it.</sub>

2024-10-24 15:36 UTC, arcady-lunarg requested changes
One minor issue, otherwise this is fine. Thanks for noticing this.

2024-10-24 15:36 UTC, arcady-lunarg commented on build_info.py
> +            formatted = datetime.datetime.fromtimestamp(timestamp, datetime.UTC).isoformat()
I think you need to use datetime.timezone.utc here, as datetime.UTC was only added in 3.11, and I'd prefer not to break compatibility with older Pythons over something so trivial.

2024-10-24 20:36 UTC, selfisekai commented on build_info.py
> +            formatted = datetime.datetime.fromtimestamp(timestamp, datetime.UTC).isoformat()
done

2024-10-30 19:53 UTC, arcady-lunarg approved these changes

2024-10-30 19:53 UTC, merged