Implement GLSL_NV_cooperative_matrix2
KhronosGroup/glslang pull request #3773
Opened 2024-10-24 20:49 UTC by jeffbolznv

2024-10-28 19:25 UTC, jeffbolznv commented
@arcady-lunarg can you take a look? I don't know how closely you looked at the internal version.

2024-10-28 22:56 UTC, arcady-lunarg commented on glslang/MachineIndependent/glslang.y
> +    }
What does the FUNCTION token do? I don't see any use of EbtFunction anywhere other than here, and I don't see any tests for the "__function" keyword. The GLSL spec also has a FUNCTION token without any explanation that I can see.

2024-10-28 23:04 UTC, jeffbolznv commented on glslang/MachineIndependent/glslang.y
> +    }
`__function` is used in the prototypes for coopMatReduceNV and coopMatLoadTensorNV for the "function pointer" function parameters. That gets mapped to this grammar rule by the KeywordMap. And then EbtFunction is used in ParseHelper and GlslangToSpv to detect and handle these function pointers.

2024-10-30 18:33 UTC, jeffbolznv commented on glslang/MachineIndependent/glslang.y
> +    }
@arcady-lunarg are there any specific changes you want in this area? It's kind of a gray area for the spec because this is really an implementation detail for how glslang handles these built-in functions, so I'm not sure it makes sense to document FUNCTION there (maybe I should remove it from the GLSL spec).

I'd like to get this merged soon to unblock other dependencies.

2024-11-01 23:20 UTC, arcady-lunarg requested changes
A few comments, and one actual thing I'd like changed, namely the spirv.hpp.
Also apparently GLSL has function pointers now, that's kind of cool.

2024-11-01 23:58 UTC, jeffbolznv commented on SPIRV/spirv.hpp
ok, I ran dos2unix and added back the `: unsigned` to the masks (including the few new masks). But I kept all the other updates to the file. I get a lot of conflicts whenever I work on a new extension and need to rebase, it would be nice if we could eventually find a way to directly use one of the upstream headers.

2024-11-01 23:59 UTC, jeffbolznv commented on SPIRV/disassemble.cpp
> +{
Yeah, I don't think there's a way to get popcount without using compiler intrinsics until C++20, so I just did this for now.

2024-11-04 16:33 UTC, arcady-lunarg approved these changes
Thanks, LGTM

2024-11-04 16:33 UTC, merged