Add warning if Forward Declaration uses layout qualifiers
KhronosGroup/glslang pull request #3775
Opened 2024-10-25 18:26 UTC by spencer-lunarg

closes https://github.com/KhronosGroup/glslang/issues/3774

Now something like

```
#version 450
#extension GL_EXT_buffer_reference : enable

layout(buffer_reference, std140) buffer StructB;
layout(buffer_reference) buffer StructB {
    vec4 x;
};

void main() {}
```

will give a warning of

`WARNING: test.comp:4: 'StructB' : the packing layout (scalar, std430, etc) is ignored when defined in forward declaration `

2024-11-06 16:05 UTC, arcady-lunarg requested changes
Could you add a test for this? There's an existing `spv.bufferhandle_Error.frag` test file you can just add a couple of lines to.

2024-11-07 18:10 UTC, spencer-lunarg commented on Test/baseResults/spv.bufferhandle_Error.frag.out
> +WARNING: 0:20: 'bufType7' : the packing layout (scalar, std430, etc) is ignored when defined in forward declaration
@arcady-lunarg was this all I needed to do for adding a test?

2024-11-08 16:16 UTC, arcady-lunarg commented on Test/baseResults/spv.bufferhandle_Error.frag.out
> +WARNING: 0:20: 'bufType7' : the packing layout (scalar, std430, etc) is ignored when defined in forward declaration
Yep, this is all.

2024-11-08 16:16 UTC, arcady-lunarg approved these changes

2024-11-08 16:16 UTC, merged